### ISSUE TITLE
App state changes (and actions) should be possible in component-did-update

### ISSUE THREAD

**Issue by kenranunderscore** [active-group/reacl#23] opened 2019-02-19 12:55 UTC
[React allows app state changes](https://reactjs.org/docs/react-component.html#componentdidupdate) in the lifecycle method `component-did-update`. This was previously enabled in Reacl in 695568b8f860eaa9bc35fac3ec8000eaf9f64ca3, but subsequently `component-did-update` broke.

The fix for `component-did-update` (ee31b29bd8ea6b34263fb978ee86d4ba1ba7b958 or 2455c8b5f58826b2f9b9f9cfd8788917a02bbae3) seems to have disabled state changes again.

Our code uses this lifecycle method to do `(reacl/return :action some-action)`.

**Comment by dfrese** [comment] 2019-02-26 09:54
> [React allows app state changes](https://reactjs.org/docs/react-component.html#componentdidupdate) in the lifecycle method `component-did-update`. 

React does not have the concept of an app-state; what they call state is solely the local-state in Reacl.
But when doing any state update in did-update, one has to be super careful to not do an endless-loop.
Also, updates don't happen without a cause - is it so inconvenient to attach that effect to the cause?

> Our code uses this lifecycle method to do `(reacl/return :action some-action)`.

Translating the continuous change of state and params back to discrete actions has a bad taste to me. Maybe you can give some more motivation? (in person is easier).

**Comment by dfrese** [comment] 2019-02-27 14:31
Fixed in 2.1.0 ('great-rewrite' branch)

**Closed as completed** 2019-02-27 14:32 UTC
